### ISSUE TITLE
Monitor banned users

### ISSUE THREAD

**Issue by Samwalton9** [LarsWesselius/Marvin#8]
After banning users it's fairly trivial for them to reset their router or get a VPN and make a new account and rejoin. Many aren't clever enough to use a different username, but it's impossible to stay on top of all the banned users and do regular searches for new accounts.

It would be useful if Marvin checked new users against the ban list and flagged a warning up (in a mod-warnings channel?) if someone joins with the username of a banned user.

**Comment by LarsWesselius** [comment]
Great idea.

**Comment by LarsWesselius** [comment]
Marvin will now watch joining users and will check their usernames and nicknames with previous bans. If there's a (partial or full) match it will post a warning to the logchannel.
